import { boolean, integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core"

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }) })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const twins = pgTable("twins", { id: uuid("id").primaryKey().defaultRandom(), userId: text("userId").notNull(), name: text("name").notNull(), status: text("status").notNull().default("draft"), referenceAssetId: uuid("referenceAssetId"), voiceAssetId: uuid("voiceAssetId"), externalTwinId: text("externalTwinId"), consentRecordedAt: timestamp("consentRecordedAt"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const mediaAssets = pgTable("media_assets", { id: uuid("id").primaryKey().defaultRandom(), userId: text("userId").notNull(), kind: text("kind").notNull(), pathname: text("pathname").notNull(), contentType: text("contentType").notNull(), size: integer("size").notNull().default(0), createdAt: timestamp("createdAt").notNull().defaultNow() })
export const renderJobs = pgTable("render_jobs", { id: uuid("id").primaryKey().defaultRandom(), userId: text("userId").notNull(), twinId: uuid("twinId"), kind: text("kind").notNull().default("video"), status: text("status").notNull().default("pending"), progress: integer("progress").notNull().default(0), stage: text("stage"), externalJobId: text("externalJobId"), error: text("error"), payload: jsonb("payload").notNull().default({}), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const videos = pgTable("videos", { id: uuid("id").primaryKey().defaultRandom(), userId: text("userId").notNull(), jobId: uuid("jobId"), twinId: uuid("twinId"), title: text("title").notNull(), status: text("status").notNull().default("processing"), outputAssetId: uuid("outputAssetId"), externalUrl: text("externalUrl"), durationSeconds: integer("durationSeconds"), tags: text("tags").array().notNull().default([]), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
