import Link from 'next/link'
import { getWorkspaceData } from '@/app/actions/data'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ArrowRight, Plus, UserRound } from 'lucide-react'

export default async function Twins() {
  const { twins } = await getWorkspaceData()
  return <div className="flex flex-col gap-8"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-primary">Presenters</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Digital twins</h1><p className="mt-3 text-muted-foreground">Manage the approved identities available to your studio.</p></div><Button render={<Link href="/app/twins/new" />}><Plus data-icon="inline-start" />New twin</Button></header>{twins.length === 0 ? <Card><CardContent className="flex min-h-[420px] flex-col items-center justify-center gap-5 text-center"><span className="flex size-16 items-center justify-center rounded-2xl border bg-muted"><UserRound className="text-primary" /></span><div><p className="text-xl font-medium">Create your first presenter</p><p className="mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">Add approved reference footage to build a reusable digital twin for your videos.</p></div><Button render={<Link href="/app/twins/new" />}>Begin setup<ArrowRight data-icon="inline-end" /></Button></CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{twins.map(twin => <Card key={twin.id} className="overflow-hidden"><div className="flex aspect-video items-center justify-center bg-muted"><UserRound className="size-10 text-muted-foreground" /></div><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>{twin.name}</CardTitle><CardDescription className="mt-2">Added {twin.createdAt.toLocaleDateString()}</CardDescription></div><span className="rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase text-muted-foreground">{twin.status}</span></div></CardHeader></Card>)}</div>}</div>
}
