import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Cpu, KeyRound, Sparkles } from 'lucide-react'

export default function Settings() {
  return <div className="flex max-w-4xl flex-col gap-8"><header><p className="font-mono text-xs uppercase tracking-[.22em] text-primary">Workspace</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Settings</h1><p className="mt-3 text-muted-foreground">Manage production services and workspace preferences.</p></header><div className="grid gap-5"><Card><CardHeader><div className="flex items-start gap-4"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/10"><Cpu className="text-primary" /></span><div><CardTitle>Render service</CardTitle><CardDescription className="mt-2">Connect the production engine used to create twins and videos.</CardDescription></div></div></CardHeader><CardContent className="flex flex-col gap-5"><div className="flex flex-col gap-2"><Label htmlFor="endpoint">Service URL</Label><Input id="endpoint" placeholder="https://render.yourstudio.com" disabled /></div><div className="flex items-center justify-between rounded-xl border p-4"><div><p className="text-sm font-medium">Production updates</p><p className="mt-1 text-xs text-muted-foreground">Receive status changes throughout each render.</p></div><Switch disabled /></div><Button className="w-fit" disabled><Cpu data-icon="inline-start" />Connect service</Button></CardContent></Card><Card><CardHeader><div className="flex items-start gap-4"><span className="flex size-11 items-center justify-center rounded-xl bg-accent/10"><Sparkles className="text-accent" /></span><div><CardTitle>Writing assistant</CardTitle><CardDescription className="mt-2">Add script drafting, translation, and production guidance.</CardDescription></div></div></CardHeader><CardContent><div className="flex items-center gap-3 rounded-xl border p-4"><KeyRound className="text-muted-foreground" /><p className="text-sm text-muted-foreground">Connect an agent service to enable writing tools.</p></div></CardContent></Card></div></div>
}
