import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import { Check, ShieldCheck, Upload, Video } from 'lucide-react'

export default function NewTwin() {
  return <div className="mx-auto flex max-w-5xl flex-col gap-8"><header><p className="font-mono text-xs uppercase tracking-[.22em] text-primary">Presenter setup</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Create a digital twin</h1><p className="mt-3 max-w-2xl text-muted-foreground">Use clear reference footage to prepare a reusable presenter for your studio.</p></header><div className="grid gap-5 lg:grid-cols-[250px_1fr]"><aside className="flex flex-col gap-2">{['Identity reference', 'Voice profile', 'Review and consent'].map((step, index) => <div key={step} className={`flex items-center gap-3 rounded-xl border p-3 ${index === 0 ? 'bg-muted text-foreground' : 'text-muted-foreground'}`}><span className="flex size-7 items-center justify-center rounded-lg bg-background font-mono text-xs">{index === 0 ? <Check className="size-3" /> : index + 1}</span><span className="text-sm font-medium">{step}</span></div>)}</aside><Card className="surface-glow"><CardHeader><CardTitle>Identity reference</CardTitle><CardDescription>Upload a clear, well-lit video with a stable camera and natural movement.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-6"><div className="flex flex-col gap-2"><Label htmlFor="name">Presenter name</Label><Input id="name" placeholder="Product presenter" /></div><label className="flex min-h-64 cursor-pointer flex-col items-center justify-center gap-4 rounded-2xl border border-dashed bg-muted/20 p-8 text-center transition-colors hover:bg-muted/40"><span className="flex size-14 items-center justify-center rounded-2xl bg-primary/10"><Upload className="text-primary" /></span><div><span className="font-medium">Choose reference video</span><span className="mt-2 block text-xs text-muted-foreground">MP4 or MOV · 30–120 seconds · up to 500 MB</span></div><Input type="file" accept="video/mp4,video/quicktime" className="sr-only" /></label><div className="rounded-2xl border bg-muted/20 p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-accent" /><div><p className="text-sm font-medium">Use approved likenesses only</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Upload footage of yourself or a person who has explicitly approved this use.</p></div></div></div><div className="flex items-start gap-3"><Checkbox id="consent" /><Label htmlFor="consent" className="leading-relaxed">I confirm I own this likeness or have explicit, documented consent to create and use this digital twin.</Label></div><Button size="lg" disabled><Video data-icon="inline-start" />Continue setup</Button></form></CardContent></Card></div></div>
}
