import Link from 'next/link'
import { getWorkspaceData } from '@/app/actions/data'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { ArrowRight, Clapperboard, Plus, Radio, Users, Video } from 'lucide-react'

export default async function Overview() {
  const data = await getWorkspaceData()
  const metrics = [{ value: data.twins.length, label: 'Digital twins', icon: Users }, { value: data.jobs.length, label: 'Productions', icon: Radio }, { value: data.videos.length, label: 'Finished videos', icon: Video }]
  return <div className="flex flex-col gap-8"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-primary">Overview</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Your production studio</h1><p className="mt-3 text-muted-foreground">Build presenters, direct videos, and manage every output.</p></div><Button render={<Link href="/app/create" />}><Plus data-icon="inline-start" />New production</Button></header>
    <section className="grid gap-4 md:grid-cols-3">{metrics.map(({ value, label, icon: Icon }) => <Card key={label} className="bg-card/70"><CardHeader className="flex-row items-center justify-between pb-2"><CardDescription>{label}</CardDescription><Icon className="text-primary" /></CardHeader><CardContent><CardTitle className="font-mono text-4xl">{value.toString().padStart(2, '0')}</CardTitle></CardContent></Card>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><CardTitle>Recent productions</CardTitle><CardDescription>Your latest render activity appears here.</CardDescription></CardHeader><CardContent>{data.jobs.length === 0 ? <div className="flex min-h-64 flex-col items-center justify-center gap-5 rounded-2xl border border-dashed bg-muted/20 p-8 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-primary/10"><Clapperboard className="text-primary" /></span><div><p className="font-medium">Create your first production</p><p className="mt-2 max-w-sm text-sm leading-relaxed text-muted-foreground">Choose a digital twin, add your script, and set the direction for your video.</p></div><Button variant="outline" render={<Link href="/app/create" />}>Open creator<ArrowRight data-icon="inline-end" /></Button></div> : <div className="flex flex-col gap-2">{data.jobs.slice(0, 5).map(job => <div key={job.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{job.stage || job.kind}</p><p className="mt-1 text-xs text-muted-foreground">{job.createdAt.toLocaleDateString()}</p></div><span className="font-mono text-xs uppercase text-muted-foreground">{job.status}</span></div>)}</div>}</CardContent></Card>
      <Card className="bg-primary text-primary-foreground"><CardHeader><CardDescription className="text-primary-foreground/70">Quick start</CardDescription><CardTitle className="text-2xl">Bring your presenter to life.</CardTitle></CardHeader><CardContent className="flex flex-col gap-8"><p className="text-sm leading-relaxed text-primary-foreground/75">Set up a digital twin from approved reference footage, then use it across every production.</p><Button variant="secondary" render={<Link href="/app/twins/new" />}>Create digital twin<ArrowRight data-icon="inline-end" /></Button></CardContent></Card></section>
  </div>
}
