import Link from 'next/link'
import { ArrowRight, AudioLines, Clapperboard, ShieldCheck, Video } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { TwinForgeLogo } from '@/components/twinforge-logo'

const features = [
  { icon: Clapperboard, title: 'Direct every frame', text: 'Shape scripts, performances, formats, and delivery from one focused production space.' },
  { icon: AudioLines, title: 'Keep your voice', text: 'Pair your digital twin with natural voice delivery across languages and campaigns.' },
  { icon: Video, title: 'Scale the studio', text: 'Move from one polished video to entire production batches without changing tools.' },
]

export default function Home() {
  return <main className="min-h-screen overflow-hidden">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><TwinForgeLogo /><nav className="flex items-center gap-2"><Button variant="ghost" render={<Link href="/sign-in" />}>Sign in</Button><Button render={<Link href="/sign-up" />}>Open studio</Button></nav></header>
    <section className="studio-grid border-y"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1fr_420px] lg:items-center lg:py-36">
      <div><p className="font-mono text-xs uppercase tracking-[.24em] text-primary">AI human video studio</p><h1 className="mt-6 max-w-5xl text-balance text-5xl font-semibold leading-[.95] tracking-[-.055em] sm:text-7xl lg:text-8xl">Your presence,<br /><span className="text-muted-foreground">built to scale.</span></h1><p className="mt-8 max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground sm:text-xl">Create expressive digital twins and turn every approved script into polished human video from a single production workspace.</p><div className="mt-10 flex flex-wrap gap-3"><Button size="lg" render={<Link href="/sign-up" />}>Create your twin<ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" render={<Link href="/sign-in" />}>Enter workspace</Button></div></div>
      <div className="surface-glow rounded-3xl border bg-card p-3"><div className="flex aspect-[4/5] flex-col justify-between rounded-2xl border bg-muted/40 p-6"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground">Twin canvas</span><span className="size-2 rounded-full bg-accent" /></div><div className="flex flex-col items-center gap-5 text-center"><span className="flex size-24 items-center justify-center rounded-full border border-primary/30 bg-primary/10"><Clapperboard className="size-9 text-primary" /></span><div><p className="text-xl font-medium">One studio. Every version.</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Your likeness, voice, scripts, and outputs stay organized around the work.</p></div></div><div className="grid grid-cols-3 gap-2 font-mono text-[9px] uppercase tracking-wider text-muted-foreground"><span>Identity</span><span>Voice</span><span>Output</span></div></div></div>
    </div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="mb-10 flex max-w-2xl flex-col gap-3"><p className="font-mono text-xs uppercase tracking-[.22em] text-primary">Studio workflow</p><h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">From identity to finished cut.</h2></div><div className="grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }, index) => <Card key={title} className="bg-card/70"><CardHeader><div className="mb-8 flex items-center justify-between"><Icon className="text-primary" /><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span></div><CardTitle>{title}</CardTitle></CardHeader><CardContent className="leading-relaxed text-muted-foreground">{text}</CardContent></Card>)}</div><div className="mt-16 flex flex-col items-start justify-between gap-6 rounded-3xl border bg-card p-8 sm:flex-row sm:items-center"><div className="flex items-start gap-4"><ShieldCheck className="mt-1 text-accent" /><div><p className="font-medium">Built around permission</p><p className="mt-1 max-w-xl text-sm leading-relaxed text-muted-foreground">Private references and explicit consent are part of every digital twin workflow.</p></div></div><Button render={<Link href="/sign-up" />}>Start creating<ArrowRight data-icon="inline-end" /></Button></div></section>
  </main>
}
