"use client"

import Link from "next/link"
import { usePathname, useRouter } from "next/navigation"
import { authClient } from "@/lib/auth-client"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Boxes, Clapperboard, Library, LogOut, Menu, Settings, Users, X } from "lucide-react"
import { useState } from "react"

const nav=[{href:"/app",label:"Overview",icon:Boxes},{href:"/app/twins",label:"Digital twins",icon:Users},{href:"/app/create",label:"Create video",icon:Clapperboard},{href:"/app/batch",label:"Batch studio",icon:Library},{href:"/app/library",label:"Library",icon:Library},{href:"/app/settings",label:"Settings",icon:Settings}]
export function AppShell({children,name}:{children:React.ReactNode;name:string}){const p=usePathname();const r=useRouter();const [open,setOpen]=useState(false);return <div className="min-h-screen bg-background text-foreground"><aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-sidebar p-4 transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><div className="flex items-center justify-between"><Link href="/app" className="font-sans text-lg font-semibold tracking-tight">TwinForge<span className="text-primary">/</span></Link><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></Button></div><nav className="mt-10 flex flex-1 flex-col gap-1">{nav.map(n=><Link key={n.href} href={n.href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2 text-sm transition-colors ${p===n.href?"bg-accent text-accent-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><n.icon className="size-4"/>{n.label}</Link>)}</nav><div className="flex items-center gap-3 border-t border-border pt-4"><Avatar><AvatarFallback>{name.slice(0,2).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">Creator workspace</p></div><Button variant="ghost" size="icon" aria-label="Sign out" onClick={async()=>{await authClient.signOut();r.push("/");r.refresh()}}><LogOut/></Button></div></aside><main className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b border-border px-4 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></Button><div className="ml-auto flex items-center gap-2"><span className="size-2 rounded-full bg-destructive"/><span className="font-mono text-xs text-muted-foreground">GPU OFFLINE</span></div></header><div className="p-4 md:p-8">{children}</div></main></div>}
