"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { authClient } from "@/lib/auth-client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
export function AuthForm({mode}:{mode:"sign-in"|"sign-up"}){const [error,setError]=useState("");const [loading,setLoading]=useState(false);const r=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));const name=String(f.get("name")||email.split("@")[0]);const result=mode==="sign-up"?await authClient.signUp.email({email,password,name}):await authClient.signIn.email({email,password});if(result.error){setError(result.error.message||"Unable to continue");setLoading(false);return}r.push("/app");r.refresh()}return <Card className="w-full max-w-md"><CardHeader><CardTitle>{mode==="sign-up"?"Create your workspace":"Welcome back"}</CardTitle><CardDescription>{mode==="sign-up"?"Start building consent-first digital humans.":"Sign in to your TwinForge studio."}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-4">{mode==="sign-up"&&<div className="flex flex-col gap-2"><Label htmlFor="name">Name</Label><Input id="name" name="name" required/></div>}<div className="flex flex-col gap-2"><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required/></div><div className="flex flex-col gap-2"><Label htmlFor="password">Password</Label><Input id="password" name="password" type="password" minLength={8} required/></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={loading}>{loading?"Please wait…":mode==="sign-up"?"Create account":"Sign in"}</Button></form></CardContent></Card>}
