'use client'
import { useMemo, useState, useTransition } from 'react'
import { Film, LoaderCircle, Search, Trash2 } from 'lucide-react'
import { deleteVideo } from '@/app/actions/data'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
type Video={id:string;title:string;status:string;createdAt:Date}
export function ProductionQueue({videos}:{videos:Video[]}){const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [pending,start]=useTransition();const shown=useMemo(()=>videos.filter(v=>(filter==='all'||v.status===filter)&&v.title.toLowerCase().includes(query.toLowerCase())),[videos,query,filter]);return <div className="flex flex-col gap-5"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-muted-foreground"/><Input aria-label="Search productions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search productions" className="pl-10"/></label><select aria-label="Filter productions" value={filter} onChange={e=>setFilter(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All statuses</option><option value="awaiting_gpu">Prepared</option><option value="completed">Completed</option><option value="failed">Failed</option></select></div>{shown.length===0?<Card><CardContent className="flex min-h-72 flex-col items-center justify-center gap-4 text-center"><Film className="text-primary"/><div><p className="font-medium">No matching productions</p><p className="mt-2 text-sm text-muted-foreground">Prepare a production or adjust the filters.</p></div></CardContent></Card>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map(video=><Card key={video.id}><div className="flex aspect-video items-center justify-center bg-muted"><Film className="text-muted-foreground"/></div><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{video.title}</CardTitle><CardDescription className="mt-2">{video.status==='awaiting_gpu'?'Prepared for GPU':video.status}</CardDescription></div><Button variant="ghost" size="icon" aria-label={`Delete ${video.title}`} disabled={pending} onClick={()=>start(()=>deleteVideo(video.id))}>{pending?<LoaderCircle className="animate-spin"/>:<Trash2/>}</Button></div></CardHeader></Card>)}</div>}</div>}
